"""Initial target schema

Revision ID: 1d6e502b46c7
Revises: 
Create Date: 2025-12-26 17:52:23.682092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6e502b46c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'signal_id'),
    sa.UniqueConstraint('timestamp', 'signal_id', name='uix_timestamp_signal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('signal')
    # ### end Alembic commands ###
